# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'AnimationTransition' do
pod 'Masonry'
pod 'RealReachability', '~> 1.1.1'
end

target 'AnimationTransitionTests' do

end

target 'AnimationTransitionUITests' do

end

